### ISSUE TITLE
Page Not Rendering after Install

### ISSUE THREAD

**Issue by unrulybeep** [jitinnair1/gradfolio#17]
So sorry about this. I should have added clearer instructions!

This is happening because of the `url` field in the `_config.yml` file. In the `_config.yml` file, the `baseurl` will be "/" followed by the name of your repo.  (like `/repo_name`). The `url` field should be used in the case of custom domains only. So you should leave it only as `""` if you are using the `username.github.io` domain. (Something like [this](https://github.com/jitinnair1/gradfolio/blob/628a2e7986a0712dcae1683432e1a1f17779f020/_config.yml))

Also, when you change the `baseurl` to `/repo_name`, when you run `jekyll serve --incremental --trace`, the localhost URL will be something like `http://127.0.0.1:4000/repo_name`

_Originally posted by @jitinnair1 in https://github.com/jitinnair1/gradfolio/discussions/12#discussioncomment-1548024_

Hello jitinnair1,

Thank you for creating this portfolio. I would like to use my unrulybeep.github.io url. I clicked the "Use this Template" button, as the README.md instructions state, but I am only able to render basic text. The project page nor any of the assets render. I am thinking it may have something to do with baseurl as you wrote in this comment to another user. I have the baseurl set to /unrulybeep.github.io. Is this an incorrect way to format the baseurl? If that appears right to you, would you be willing to suggest another way for me to resolve my problem?

**Comment by unrulybeep** [comment]
Oh, I'm sorry. 😕 I meant to start a discussion, not an issue. Would you prefer me to close this and report in the discussions?

**Comment by jitinnair1** [comment]
Hi @unrulybeep,

I just checked out your repo and I think it is breaking because of a minor typo in your [`variables.scss`](https://github.com/unrulybeep/unrulybeep.github.io/blob/ee3e7e227b328b7da90594fbffb0467d876e9211/assets/css/_sass/variables.scss#L11) file. 

Commenting using `//` should fix this. Let me know if it still doesn't work.

**Comment by unrulybeep** [comment]
Thank you for your correction! I updated the file and I am still experiencing the same result.

**Comment by jitinnair1** [comment]
Can you try this configuration:

```yaml
baseurl: /
url: "https://unrulybeep.github.io"
```

I think this should work. Please try and let me know if this fixes the problem.

**Comment by unrulybeep** [comment]
Your suggestion worked for me. Thanks for the assistance.
